### ISSUE TITLE
Exception on Load

### ISSUE THREAD

**Issue by michaelahlers** [aerisweather/googlemaps-amd#1]
Not sure if this is your bug, so guidance is appreciated if it's my usage.

I get `Uncaught TypeError: Object #<Object> has no method 'Load'` from line 54 in `main.js?_=1393466880871`. Have Google changed their loader recently? I've also had problems using my previous method with the `async` plugin.

My use case is trivial—simply invoking the `googlemaps` plugin as a dependency as documented.

**Comment by eschwartz** [comment]
Hmm... I'm having a hard time reproducing that error. Can you show me your code? What's in your AMD configuration (ie. `require.config`)? Are you using RequireJS, or another AMD loader?

Do you have a stack trace for the error? If you don't know how to do this in your browser dev tools, you can throw this in your script:

``` javascript
window.onerror = function(message, file, line, char, error) {
  console.log(error.message, error.stack);
};
```

Let me know what that prints out.

Take a look at the [test specs](https://github.com/hamweather/googlemaps-amd/tree/master/test) for the plugin. There's an [integration test](https://github.com/hamweather/googlemaps-amd/blob/master/test/spec/googlemaps-integration.js) which checks that the plugin is loading in `google.maps` without errors. I just ran it, and it's passing, so I don't think there's been any breaking change from Google.

**Comment by rafaelfaria** [comment]
I'm getting the same problem. RequireJS 2.1.6

**Comment by eschwartz** [comment]
@rafaelfaria See my comment above -- can you give more more information about the error?

**Comment by rafaelfaria** [comment]
Well. I managed to fix it.

Well, not really fix it, but my problem was that I was using another async plugin (https://github.com/caolan/async) and was always under the impression that we were talking about the same one when it mentioned "async".

I had to make a slightly change to the name of the async plugin that is specific for google load and now it's working fine. I didn't even had to use this module. All I had to do was

```
require(['asyncGoogle!http://maps.google.com/maps/api/js?sensor=false'], function(){
});
```

And as asyncGoogle I'm talking about this one: https://github.com/millermedeiros/requirejs-plugins/blob/master/src/async.js

Hope it helps.

**Comment by eschwartz** [comment]
Got it -- glad you were able to track that one down. @michaelahlers -- could this be the same issue you are having?

If you have a naming conflict with your AMD modules, you should be able to do something like this:

``` javascript
require.config({
  map: {
    // Tell the googlemaps module to use the
    // 'async' module from millermedeiros/requirejs-plugins
    googlemaps: {
      async: 'bower_components/requirejs-plugins/src/async'
    },

    // Everyone else will get caolan/async
    // when they require 'async'
    '*': {
      async: 'bower_components/caolin_async/lib/async'
    }
  }
});
```

Did you find the docs unclear about which async library to use? Let me know, and I can update them (or just send me a pull request).

---

Using the [async! plugin](https://github.com/millermedeiros/requirejs-plugins) directly is probably the way to go in most situations. I created this plugin out of the need to allow consumers of [my library](https://github.com/hamweather/aerisjs) to configure their own Google Maps API key. [See my note in the (updated) README.md.](https://github.com/hamweather/googlemaps-amd/blob/master/README.md#why-not-use-the-async-plugin)
