### ISSUE TITLE
SensorNotRequired Error

### ISSUE THREAD

**Issue by pandauxstudio** [aerisweather/googlemaps-amd#5]
I am receiving the following warning in Chrome:
SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages

The warning is explained here:
https://developers.google.com/maps/documentation/javascript/error-messages

"The sensor parameter is no longer required for the Google Maps JavaScript API. It won't prevent the Google Maps JavaScript API from working correctly, but we recommend that you remove the sensor parameter from the script element."

This has been causing really weird problems for me causing my app to crash.

I managed to resolve this by deleting the following lines, would be great if you can apply this fix please.
https://github.com/aerisweather/googlemaps-amd/blob/master/src/googlemaps.js#L118

**Comment by eschwartz** [comment]
Sure -- if you submit a pull request, I'll merge it in

**Comment by pandauxstudio** [comment]
Please disregard this, I discovered that the issues I experienced were introduced by switching from Bootstrap Tabs to jQuery Tabs, most likely to do with history.pushState calls that I was making to update the URL.
